title: Klotski
description: some random description
show_downloads: false
theme: jekyll-theme-architect

authors:
  roto65:
    name: Alessandro Rotondo
    email: alessandro.rotondo@studenti.unipd.it