title: Klotski
description: some random description
show_downloads: false
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jeckyll-remote-theme

author:
  name: Alessandro Rotondo
  url: https://github.com/roto65

